Реквест Максимов, фреймворк Грушевского
RMS1t/Gryschewsky_style pull request #3
Opened 2023-11-05 13:31 UTC by RMS1t

Доработаю  дополнительный пакет очно в понедельник

2023-11-05 14:25 UTC, RetmixX requested changes
type add

2023-11-05 14:25 UTC, RetmixX commented on dev-compose/docker-compose.yml
> +      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
Уважаемо

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/app/Middlewares/TrimMiddleware.php
> +    public function handle(Request $request)
type return

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/app/Model/User.php
> +    public function findIdentity(int $id)
type

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Auth/Auth.php
> +    public static function user()
type

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Auth/IdentityInterface.php
> +    public function findIdentity(int $id);
type return

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Request.php
> +    public function get($field)
type return

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Route.php
> +    private $currentHttpMethod;
type

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Session.php
> +    public static function get($name)
type

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Session.php
> +    public static function clear($name)
type

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Validator/AbstractValidator.php
> +    protected $value;
type

2023-11-05 14:25 UTC, RetmixX commented on pop-it-mvc/core/Src/Validator/AbstractValidator.php
> +    public function validate()
type

2023-11-05 16:26 UTC, jurapro requested changes
- [ ] исправить замечания от Андрея
- [x] не увидел код решенного с помощью этого фреймворка фрагмента тестового задания (функционала гостя). нужно сделать

2023-11-07 16:57 UTC, jurapro approved these changes
принято

2023-11-08 05:59 UTC, merged